version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    container_name: api-football-container
    image: api-football-image
    restart: always
    networks:
      - api-football

networks:
  api-football:
    external: true